name: publish to registry
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint && pnpm build
      - name: Create release and publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
